Feature/wxt/postpage
allspark-studio/inxupt-frontend pull request #20
Opened 2023-05-29 14:58 UTC by xWXBB

2023-06-13 16:05 UTC, Marstonchan requested changes

2023-06-13 16:05 UTC, Marstonchan commented on project.config.json
> +  "appid": "wxfdb66d177b40d675",
这里不需要修改 `wx41157022e04c27bb` 是我们的 appid，改了的话会导致获取user信息失败

2023-06-13 16:05 UTC, Marstonchan commented on src/app.ts
> +App.use(Textarea);
业务组件不要在这里使用 App.use()，在页面组件中 import. ConfigProvider 是我手误多引用了，顺便也删除吧。

2023-06-13 16:05 UTC, Marstonchan commented on src/assets/postPage_popupicon.png
这个图标在哪引用了？

2023-06-13 16:05 UTC, Marstonchan commented on src/pages/post/type.d.ts
类型定义统一放到types目录下吧，而且不用 .d.ts 的直接 .ts 就可以了

2023-06-13 16:05 UTC, Marstonchan commented on src/pages/post/type.d.ts
> +export interface topicModel {
所有类型定义使用大驼峰形式命名 `TopicModel`

2023-06-13 16:05 UTC, Marstonchan commented on src/pages/post/type.d.ts
> +export interface postDataFormat {
同上

2023-06-13 16:05 UTC, Marstonchan commented on src/service/post_service.ts
> +    const { data } = await axios.post<CustomResponseData<PostResponse>>(url, dataParam);
这个类型定义很nice!

2023-06-13 17:22 UTC, xWXBB commented on src/assets/postPage_popupicon.png
这个是之前那个弹窗里面的icon，现在没有弹窗这个需求了，该图标已经删除。

2023-06-16 17:03 UTC, Marstonchan requested changes

2023-06-16 17:03 UTC, Marstonchan commented on src/pages/post/index.vue
> +        <ImageList
taro更推荐使用中划线方式：`<image-list></image-list>`

2023-06-16 17:03 UTC, Marstonchan commented on src/pages/post/index.vue
> +  if (ifTextareaContent() === true) {
同时需要禁用提交按钮，button 有个 disabled 属性。

2023-06-16 17:03 UTC, Marstonchan commented on src/assets/add.png
这两个图片没有用到吧？没有用到的话就删掉吧，不然包体积会过大的

2023-06-16 17:03 UTC, Marstonchan commented on src/assets/delbtn.png
同上

2023-06-17 17:52 UTC, Marstonchan approved these changes

2023-06-17 17:53 UTC, merged