新增TimeAgo组件
allspark-studio/inxupt-frontend pull request #4
Opened 2023-04-25 15:13 UTC by 921l

增加TimeAgo组件

2023-04-25 16:07 UTC, Marstonchan requested changes

2023-04-25 16:07 UTC, Marstonchan commented on project.config.json
> +  "appid": "wx3d314a0c7e632b0e",
不要把微信小程序的APPID写在代码里

2023-04-25 16:07 UTC, Marstonchan commented on src/components/TimeAgo.vue
> +      // console.log(differYears2)
把测试代码删掉哦

2023-04-25 16:07 UTC, Marstonchan commented on src/pages/index/index.vue
> +      >
这个是自动格式化成这样了吗？

2023-04-25 16:07 UTC, Marstonchan commented on src/pages/index/index.vue
暂时不要改动这个文件

2023-04-25 16:09 UTC, 921l commented on src/pages/index/index.vue
> +      >
对

2023-05-03 14:44 UTC, 921l commented
修改TimeAgo组件，更改dayjs配置

2023-05-04 11:44 UTC, Marstonchan approved these changes
LGTM

2023-05-04 11:44 UTC, merged